//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

         
// USER INCLUDES			
#include <SI_EFM8BB1_Register_Enums.h>
#include "wireless_recv.h"
#include "logic.h"
#include "wireless_led.h"
#include "key.h"

//-----------------------------------------------------------------------------
// PCA0_ISR
//-----------------------------------------------------------------------------
//
// PCA0 ISR Content goes here. Remember to clear flag bits:
// PCA0CN0::CCF0 (PCA Module 0 Capture/Compare Flag)
// PCA0CN0::CCF1 (PCA Module 1 Capture/Compare Flag)
// PCA0CN0::CCF2 (PCA Module 2 Capture/Compare Flag)
// PCA0CN0::CF (PCA Counter/Timer Overflow Flag)
// PCA0PWM::COVF (Cycle Overflow Flag)
//
// This is the ISR for the PCA.  It handles the case when a capture occurs on
// channel 0, and updates the variables to reflect the new capture information.
//10us
//-----------------------------------------------------------------------------


SI_INTERRUPT (PCA0_ISR, PCA0_IRQn)
{
   static uint16_t current_capture_value, previous_capture_value;
   static uint16_t capture_period = 0;
   if (PCA0CN0_CCF0)                   // If Module 0 caused the interrupt
   {
	   PCA0CN0_CCF0 = 0;                // Clear module 0 interrupt flag.
	  current_capture_value = PCA0CP0;
	  capture_period = current_capture_value - previous_capture_value;
	  previous_capture_value = current_capture_value;
	  saveCaptureValue(capture_period);
   }
   else                                // Interrupt was caused by other bits.
   {
	  PCA0CN0 &= ~0x86;                // Clear other interrupt flags for PCA
   }
}

//-----------------------------------------------------------------------------
// TIMER2_ISR
//-----------------------------------------------------------------------------
//
// TIMER2 ISR Content goes here. Remember to clear flag bits:
// TMR2CN0::TF2H (Timer # High Byte Overflow Flag)
// TMR2CN0::TF2L (Timer # Low Byte Overflow Flag)
// 2ms
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER2_ISR, TIMER2_IRQn)
{
	analyzeRfData();
	TMR2CN0_TF2H = 0;
}

//-----------------------------------------------------------------------------
// TIMER3_ISR
//-----------------------------------------------------------------------------
//
// TIMER3 ISR Content goes here. Remember to clear flag bits:
// TMR3CN0::TF3H (Timer # High Byte Overflow Flag)
// TMR3CN0::TF3L (Timer # Low Byte Overflow Flag)
// 10ms
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER3_ISR, TIMER3_IRQn)
{
    Key_Action();
    
	//timerout_cnt++;
    clkIntCnt ++;
   
	TMR3CN0 &= 0x7f;
}


//-----------------------------------------------------------------------------
// UART0_ISR
//-----------------------------------------------------------------------------
//
// UART0 ISR Content goes here. Remember to clear flag bits:
// SCON0::RI (Receive Interrupt Flag)
// SCON0::TI (Transmit Interrupt Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (UART0_ISR, UART0_IRQn)
{

}


//-----------------------------------------------------------------------------
// TIMER1_ISR
//-----------------------------------------------------------------------------
//
// TIMER1 ISR Content goes here. Remember to clear flag bits:
// TCON::TF1 (Timer 1 Overflow Flag)
//100us
//-----------------------------------------------------------------------------


SI_INTERRUPT (TIMER1_ISR, TIMER1_IRQn)
{

}

